"""Build the DobotStudio-compatible, two-file RPA2 controller project.

The maintained arm implementation deliberately remains modular in the repository.
DobotStudio, however, accepts only ``main.py`` and ``var.py`` in the observed
project workflow. This builder inlines the reviewed protocol and service code
into one self-contained ``main.py`` without changing the runtime policy. The
two executable code files still need DobotStudio's project metadata for import.
"""

import argparse
import hashlib
import pathlib


ROOT = pathlib.Path(__file__).resolve().parents[2]
RUNTIME = ROOT / "src" / "robot_arm" / "runtime"
PROTOCOL = ROOT / "protocol" / "motion_link.py"
OUTPUT_FILES = ("main.py", "var.py", "prj.json", "point.json")
PROJECT_METADATA = '{"main":"main.py","teach":"point.json","var":"var.py","submain":[],"type":"Python"}\n'
EMPTY_TEACH_POINTS = "[]\n"


def _read(path):
    return path.read_text(encoding="utf-8")


def _without(text, line, source):
    if text.count(line) != 1:
        raise ValueError("unexpected_import_in_%s" % source)
    return text.replace(line, "", 1)


def build_main():
    """Return a standalone controller entry point from the reviewed sources."""
    protocol = _read(PROTOCOL)
    faults = _without(_read(RUNTIME / "arm_faults.py"), "from motion_link import encode_fields, FAULT_FIELDS\n", "arm_faults")
    service = _read(RUNTIME / "arm_motion_service.py")
    entry = _read(RUNTIME / "main.py")

    service = _without(
        service,
        "from motion_link import FrameStreamDecoder, MotionLinkError, decode_fields, encode_fields, encode_frame\n",
        "arm_motion_service",
    )
    service = _without(service, "from arm_faults import ArmFault, ControllerFaultAccess, controller_state_payload, fault_record, fault_payload\n", "arm_motion_service")
    entry = _without(
        entry,
        "from arm_motion_service import ArmMotionService, ArmSafetyPolicy, DobotControllerApi\n",
        "main",
    )
    entry = _without(entry, "from var import *\n", "main")
    if "from motion_link import" in service or "from arm_motion_service import" in entry:
        raise ValueError("unresolved_internal_import")

    digest = hashlib.sha256((protocol + faults + service + entry).encode("utf-8")).hexdigest()[:16]
    return "\n".join((
        "# Generated by tools/robot_arm/build_dobotstudio_project.py.",
        "# Source digest: %s. Do not edit this file; edit reviewed source and rebuild." % digest,
        "# Default policy remains deny-all: var.py sets MOTION_ENABLED = False.",
        "",
        protocol.rstrip(),
        "",
        faults.rstrip(),
        "",
        service.rstrip(),
        "",
        "from var import *",
        "",
        entry.rstrip(),
        "",
    ))


def _yolo_var_source():
    source = _read(RUNTIME / "var.py")
    marker = "YOLO_MODE = False"
    if source.count(marker) != 1:
        raise ValueError("unexpected_yolo_policy")
    return source.replace(marker, "YOLO_MODE = True", 1)


def build(output, yolo=False):
    """Write two code files plus the required DobotStudio project metadata."""
    output = pathlib.Path(output)
    output.mkdir(parents=True, exist_ok=True)
    unexpected = [item.name for item in output.iterdir() if item.name not in OUTPUT_FILES]
    if unexpected:
        raise ValueError("output_directory_contains_unexpected_files")
    (output / "main.py").write_text(build_main(), encoding="utf-8", newline="\n")
    policy = _yolo_var_source() if yolo else _read(RUNTIME / "var.py")
    (output / "var.py").write_text(policy, encoding="utf-8", newline="\n")
    (output / "prj.json").write_text(PROJECT_METADATA, encoding="utf-8", newline="\n")
    (output / "point.json").write_text(EMPTY_TEACH_POINTS, encoding="utf-8", newline="\n")
    return tuple(output / name for name in OUTPUT_FILES)


def main():
    parser = argparse.ArgumentParser(description="Build a DobotStudio RPA2 project with two code files.")
    parser.add_argument("--output", required=True, type=pathlib.Path, help="empty/new output directory")
    parser.add_argument("--yolo", action="store_true", help="build repeatable manual engineering control")
    args = parser.parse_args()
    for item in build(args.output, yolo=args.yolo):
        print(item)


if __name__ == "__main__":
    main()
